### ISSUE TITLE
scripts/open_playground not working out of the box on windows

### ISSUE THREAD

**Issue by kevinramharak** [gojutin/typescript-playground-plugin-react#6]
Probably depends on `$PATH` and the name of the google binary but i had to change:
```js
exec(`open-cli ${PLAYGROUND_URL} -- 'google chrome'`
```
to
```js
exec(`open-cli ${PLAYGROUND_URL} -- chrome`
```

Any idea how to make this work cross environment?

*edit:*
And the link seems to be update to:
```ts
const PLAYGROUND_URL = "https://www.typescriptlang.org/play";
```

**Comment by just214** [comment]
I just updated pushed an update with the updated link and script. I don't have windows to test it, but hopefully that works. Thanks for reporting.
